name: notes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: ^3.7.0-41.0.dev
 
dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_bloc: ^9.0.0
  intl: ^0.20.2

dev_dependencies:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
 
flutter:

   
  uses-material-design: true
 